2025-08-07 11:11:46 GMT [7]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-08-07 11:11:46 GMT [7]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-07 11:11:46 GMT [7]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-08-07 11:11:46 GMT [7]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-07 11:11:46 GMT [12]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-08-07 11:10:53 GMT
2025-08-07 11:11:46 GMT [12]: [2-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-08-07 11:11:46 GMT [12]: [3-1] user=,db=,app=,client= LOG:  redo starts at 0/400D7F0
2025-08-07 11:11:46 GMT [12]: [4-1] user=,db=,app=,client= LOG:  invalid record length at 0/400EBE8: expected at least 24, got 0
2025-08-07 11:11:46 GMT [12]: [5-1] user=,db=,app=,client= LOG:  redo done at 0/400EBB0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 11:11:46 GMT [10]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-08-07 11:11:46 GMT [10]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.009 s, total=0.014 s; sync files=3, longest=0.006 s, average=0.003 s; distance=5 kB, estimate=5 kB; lsn=0/400EBE8, redo lsn=0/400EBE8
2025-08-07 11:11:46 GMT [7]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:11:46 GMT [15]: [1-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:11:46 GMT [15]: [2-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:11:47 GMT [15]: [3-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:11:47 GMT [15]: [4-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:11:48 GMT [15]: [5-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:11:48 GMT [15]: [6-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:11:48 GMT [15]: [7-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:11:56 GMT [24]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:11:56 GMT [24]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:11:56 GMT [24]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:11:56 GMT [24]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  database "testdb" already exists
2025-08-07 11:11:56 GMT [24]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE DATABASE testdb
2025-08-07 11:11:56 GMT [24]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.005 user=postgres database=postgres host=[local]
2025-08-07 11:11:56 GMT [26]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:11:56 GMT [26]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:11:56 GMT [26]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:11:56 GMT [26]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  role "replicator" already exists
2025-08-07 11:11:56 GMT [26]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER replicator WITH REPLICATION LOGIN PASSWORD 'replicator'
2025-08-07 11:11:56 GMT [26]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:11:56 GMT [28]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:11:56 GMT [28]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:11:56 GMT [28]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:11:56 GMT [28]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  role "efm" already exists
2025-08-07 11:11:56 GMT [28]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER efm WITH LOGIN PASSWORD 'efm'
2025-08-07 11:11:56 GMT [28]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-07 11:11:56 GMT [30]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:11:56 GMT [30]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:11:56 GMT [30]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:11:56 GMT [30]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.011 user=postgres database=postgres host=[local]
2025-08-07 11:11:57 GMT [162]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=59352
2025-08-07 11:11:57 GMT [162]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-07 11:11:57 GMT [162]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-07 11:11:57 GMT [162]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.046 user=efm database=postgres host=172.20.0.10 port=59352
2025-08-07 11:12:01 GMT [181]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=52492
2025-08-07 11:12:01 GMT [181]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-07 11:12:01 GMT [181]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=walreceiver
2025-08-07 11:12:16 GMT [189]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:12:16 GMT [189]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:12:16 GMT [189]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:12:16 GMT [189]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:12:46 GMT [203]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:12:46 GMT [203]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:12:46 GMT [203]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:12:46 GMT [203]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:12:48 GMT [15]: [8-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:12:48 GMT [15]: [9-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:12:49 GMT [15]: [10-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:12:49 GMT [15]: [11-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:12:49 GMT [181]: [4-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 LOG:  unexpected EOF on standby connection
2025-08-07 11:12:49 GMT [181]: [5-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 STATEMENT:  START_REPLICATION 0/4000000 TIMELINE 1
2025-08-07 11:12:49 GMT [181]: [6-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 LOG:  disconnection: session time: 0:00:48.108 user=replicator database= host=172.20.0.11 port=52492
