2025-08-07 11:26:22 GMT [7]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-08-07 11:26:22 GMT [7]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-07 11:26:22 GMT [7]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-08-07 11:26:22 GMT [7]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-07 11:26:22 GMT [12]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-08-07 11:22:05 GMT
2025-08-07 11:26:22 GMT [12]: [2-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-08-07 11:26:22 GMT [12]: [3-1] user=,db=,app=,client= LOG:  redo starts at 0/4012FF0
2025-08-07 11:26:22 GMT [12]: [4-1] user=,db=,app=,client= LOG:  invalid record length at 0/4014778: expected at least 24, got 0
2025-08-07 11:26:22 GMT [12]: [5-1] user=,db=,app=,client= LOG:  redo done at 0/4014740 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 11:26:22 GMT [10]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-08-07 11:26:22 GMT [10]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.064 s, total=0.078 s; sync files=3, longest=0.060 s, average=0.022 s; distance=6 kB, estimate=6 kB; lsn=0/4014778, redo lsn=0/4014778
2025-08-07 11:26:22 GMT [7]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:26:22 GMT [15]: [1-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:26:22 GMT [15]: [2-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:26:23 GMT [15]: [3-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:26:23 GMT [15]: [4-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:26:24 GMT [15]: [5-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:26:24 GMT [15]: [6-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:26:24 GMT [15]: [7-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:26:32 GMT [24]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:26:32 GMT [24]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:26:32 GMT [24]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:26:32 GMT [24]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  database "testdb" already exists
2025-08-07 11:26:32 GMT [24]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE DATABASE testdb
2025-08-07 11:26:32 GMT [24]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.006 user=postgres database=postgres host=[local]
2025-08-07 11:26:32 GMT [26]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:26:32 GMT [26]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:26:32 GMT [26]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:26:32 GMT [26]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  role "replicator" already exists
2025-08-07 11:26:32 GMT [26]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER replicator WITH REPLICATION LOGIN PASSWORD 'replicator'
2025-08-07 11:26:32 GMT [26]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:26:32 GMT [28]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:26:32 GMT [28]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:26:32 GMT [28]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:26:32 GMT [28]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  role "efm" already exists
2025-08-07 11:26:32 GMT [28]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER efm WITH LOGIN PASSWORD 'efm'
2025-08-07 11:26:32 GMT [28]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-07 11:26:32 GMT [30]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:26:32 GMT [30]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:26:32 GMT [30]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:26:32 GMT [30]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.008 user=postgres database=postgres host=[local]
2025-08-07 11:26:33 GMT [162]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=33698
2025-08-07 11:26:33 GMT [162]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-07 11:26:33 GMT [162]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-07 11:26:36 GMT [162]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:03.187 user=efm database=postgres host=172.20.0.10 port=33698
2025-08-07 11:26:37 GMT [207]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=47012
2025-08-07 11:26:37 GMT [207]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-07 11:26:37 GMT [207]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=walreceiver
2025-08-07 11:26:52 GMT [215]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:26:52 GMT [215]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:26:52 GMT [215]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:26:52 GMT [215]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-07 11:27:22 GMT [229]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:27:22 GMT [229]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:27:22 GMT [229]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:27:22 GMT [229]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:27:24 GMT [15]: [8-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:27:24 GMT [15]: [9-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:27:25 GMT [15]: [10-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:27:25 GMT [15]: [11-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:27:26 GMT [15]: [12-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:27:26 GMT [15]: [13-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:27:26 GMT [15]: [14-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:27:28 GMT [334]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:27:28 GMT [334]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:27:28 GMT [334]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:27:28 GMT [334]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-07 11:27:28 GMT [341]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=::1 LOG:  connection received: host=::1 port=35386
2025-08-07 11:27:28 GMT [348]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:27:28 GMT [348]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:27:28 GMT [348]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 11:27:28 GMT [348]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-07 11:27:29 GMT [355]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:27:29 GMT [355]: [2-1] user=postgres,db=testdb,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:27:29 GMT [355]: [3-1] user=postgres,db=testdb,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=testdb application_name=psql
2025-08-07 11:27:29 GMT [355]: [4-1] user=postgres,db=testdb,app=psql,client=[local] ERROR:  relation "test_replication" does not exist at character 37
2025-08-07 11:27:29 GMT [355]: [5-1] user=postgres,db=testdb,app=psql,client=[local] STATEMENT:  SELECT id, message, created_at FROM test_replication ORDER BY created_at DESC LIMIT 3;
2025-08-07 11:27:29 GMT [355]: [6-1] user=postgres,db=testdb,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=testdb host=[local]
2025-08-07 11:27:52 GMT [363]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:27:52 GMT [363]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:27:52 GMT [363]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:27:52 GMT [363]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:28:22 GMT [372]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:28:22 GMT [372]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:28:22 GMT [372]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:28:22 GMT [372]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:28:26 GMT [15]: [15-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:28:26 GMT [15]: [16-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:28:27 GMT [15]: [17-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:28:27 GMT [15]: [18-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:28:28 GMT [15]: [19-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:28:28 GMT [15]: [20-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:28:28 GMT [15]: [21-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:28:53 GMT [387]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:28:53 GMT [387]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:28:53 GMT [387]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:28:53 GMT [387]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:29:23 GMT [396]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:29:23 GMT [396]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:29:23 GMT [396]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:29:23 GMT [396]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:29:28 GMT [15]: [22-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:29:28 GMT [15]: [23-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:29:29 GMT [15]: [24-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:29:29 GMT [15]: [25-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:29:30 GMT [15]: [26-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:29:30 GMT [15]: [27-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:29:30 GMT [15]: [28-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:29:53 GMT [411]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:29:53 GMT [411]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:29:53 GMT [411]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:29:53 GMT [411]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:30:23 GMT [420]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:30:23 GMT [420]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:30:23 GMT [420]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:30:23 GMT [420]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:30:30 GMT [15]: [29-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:30:30 GMT [15]: [30-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:30:31 GMT [15]: [31-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:30:31 GMT [15]: [32-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:30:32 GMT [15]: [33-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:30:32 GMT [15]: [34-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:30:32 GMT [15]: [35-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:30:53 GMT [435]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:30:53 GMT [435]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:30:53 GMT [435]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:30:53 GMT [435]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 11:31:22 GMT [10]: [3-1] user=,db=,app=,client= LOG:  checkpoint starting: time
2025-08-07 11:31:23 GMT [10]: [4-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.110 s, sync=0.012 s, total=0.148 s; sync files=2, longest=0.008 s, average=0.006 s; distance=6 kB, estimate=6 kB; lsn=0/40160B0, redo lsn=0/4016058
2025-08-07 11:31:23 GMT [444]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:31:23 GMT [444]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:31:23 GMT [444]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:31:23 GMT [444]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:31:33 GMT [15]: [36-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:31:33 GMT [15]: [37-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:31:34 GMT [15]: [38-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:31:34 GMT [15]: [39-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:31:35 GMT [15]: [40-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:31:35 GMT [15]: [41-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:31:35 GMT [15]: [42-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:31:53 GMT [459]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:31:53 GMT [459]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:31:53 GMT [459]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:31:53 GMT [459]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-07 11:32:23 GMT [474]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:32:23 GMT [474]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:32:23 GMT [474]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:32:23 GMT [474]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:32:35 GMT [15]: [43-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:32:35 GMT [15]: [44-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:32:36 GMT [15]: [45-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:32:36 GMT [15]: [46-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:32:37 GMT [15]: [47-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:32:37 GMT [15]: [48-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:32:37 GMT [15]: [49-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:32:53 GMT [489]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:32:53 GMT [489]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:32:53 GMT [489]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:32:53 GMT [489]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-07 11:33:23 GMT [498]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:33:23 GMT [498]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:33:23 GMT [498]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:33:23 GMT [498]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:33:37 GMT [15]: [50-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:33:37 GMT [15]: [51-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:33:38 GMT [15]: [52-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:33:38 GMT [15]: [53-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 11:33:39 GMT [15]: [54-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 11:33:39 GMT [15]: [55-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 11:33:39 GMT [15]: [56-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 11:33:52 GMT [207]: [4-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 LOG:  unexpected EOF on standby connection
2025-08-07 11:33:52 GMT [207]: [5-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 STATEMENT:  START_REPLICATION 0/4000000 TIMELINE 1
2025-08-07 11:33:52 GMT [207]: [6-1] user=replicator,db=[unknown],app=walreceiver,client=172.20.0.11 LOG:  disconnection: session time: 0:07:14.636 user=replicator database= host=172.20.0.11 port=47012
2025-08-07 11:33:53 GMT [513]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 11:33:53 GMT [513]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 11:33:53 GMT [513]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 11:33:53 GMT [513]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
